from collections.abc import Callable, Iterator, Mapping, Sequence
from os import PathLike
from typing import Any, TypeAlias

import numpy as np
import numpy.typing as npt

__version__: str

ArrayLike = npt.ArrayLike
TableLike: TypeAlias = (
    Any  # Arrow PyCapsule object (pyarrow, polars, Table, PointSet) or Mapping[str, ArrayLike]
)
Path: TypeAlias = str | PathLike[str]
Holes: TypeAlias = Sequence[int] | Sequence[str] | ArrayLike

class Table:
    def __init__(self, data: TableLike | Mapping[str, ArrayLike]) -> None: ...
    @property
    def num_rows(self) -> int: ...
    @property
    def column_names(self) -> list[str]: ...
    def column(self, name: str) -> npt.NDArray[np.float64] | list[str | None]: ...
    def __getitem__(self, name: str) -> npt.NDArray[np.float64] | list[str | None]: ...
    def __len__(self) -> int: ...
    def to_polars(self) -> Any: ...
    def to_pyarrow(self) -> Any: ...
    def to_pandas(self) -> Any: ...
    def __arrow_c_schema__(self) -> object: ...
    def __arrow_c_array__(self, requested_schema: object | None = None) -> tuple[object, object]: ...
    def __arrow_c_stream__(self, requested_schema: object | None = None) -> object: ...

class PointSet:
    def __init__(
        self,
        coords: ArrayLike,
        attributes: TableLike | Mapping[str, ArrayLike] | None = None,
        crs: str | None = None,
    ) -> None: ...
    @staticmethod
    def from_table(
        table: TableLike, x: str = "X", y: str = "Y", z: str | None = None, crs: str | None = None
    ) -> PointSet: ...
    @property
    def coords(self) -> npt.NDArray[np.float64]: ...
    @property
    def attributes(self) -> Table: ...
    @property
    def crs(self) -> str | None: ...
    def to_table(self) -> Table: ...
    def __getitem__(self, name: str) -> npt.NDArray[np.float64] | list[str | None]: ...
    def __len__(self) -> int: ...
    def with_column(self, name: str, values: ArrayLike) -> PointSet: ...
    def __arrow_c_stream__(self, requested_schema: object | None = None) -> object: ...

class BlockModel:
    def __init__(
        self,
        origin: Sequence[float],
        size: Sequence[float],
        count: Sequence[int],
        rotation: tuple[float, float, float] = (0.0, 0.0, 0.0),
        attributes: TableLike | Mapping[str, ArrayLike] | None = None,
        index: npt.NDArray[np.uint64] | None = None,
        crs: str | None = None,
    ) -> None: ...
    @property
    def origin(self) -> list[float]: ...
    @property
    def size(self) -> list[float]: ...
    @property
    def count(self) -> list[int]: ...
    @property
    def rotation(self) -> list[float]: ...
    @property
    def crs(self) -> str | None: ...
    @property
    def index(self) -> npt.NDArray[np.uint64] | None: ...
    @property
    def centroids(self) -> npt.NDArray[np.float64]: ...
    @property
    def attributes(self) -> Table: ...
    def mask(self, keep: npt.NDArray[np.bool_]) -> BlockModel: ...
    def to_regular(self) -> BlockModel: ...
    def with_column(self, name: str, values: ArrayLike) -> BlockModel: ...
    @property
    def extents(self) -> npt.NDArray[np.float64] | None: ...
    @property
    def volumes(self) -> npt.NDArray[np.float64]: ...
    @staticmethod
    def subblocked(
        origin: Sequence[float],
        size: Sequence[float],
        count: Sequence[int],
        parent: npt.NDArray[np.uint64],
        extents: ArrayLike,
        rotation: tuple[float, float, float] = (0.0, 0.0, 0.0),
        subgrid: tuple[int, int, int] | None = None,
        attributes: TableLike | Mapping[str, ArrayLike] | None = None,
        crs: str | None = None,
    ) -> BlockModel: ...
    def to_table(self) -> Table: ...
    def __getitem__(self, name: str) -> npt.NDArray[np.float64] | list[str | None]: ...
    def __len__(self) -> int: ...
    def __arrow_c_stream__(self, requested_schema: object | None = None) -> object: ...

def read_csv(path: Path, nodata: Sequence[str] | None = None, delimiter: str = ",") -> Table: ...
def write_csv(path: Path, table: TableLike) -> None: ...
def read_gslib(path: Path, nodata: Sequence[str] | None = None) -> Table: ...
def write_gslib(path: Path, table: TableLike, missing: float = -999.0) -> None: ...

class NormalScore:
    def __init__(self, tails: tuple[float, float] | None = None) -> None: ...
    def fit(self, values: ArrayLike, weights: ArrayLike | None = None) -> NormalScore: ...
    def fit_transform(
        self, values: ArrayLike, weights: ArrayLike | None = None
    ) -> npt.NDArray[np.float64]: ...
    def transform(self, values: ArrayLike) -> npt.NDArray[np.float64]: ...
    def inverse_transform(self, scores: ArrayLike) -> npt.NDArray[np.float64]: ...
    @property
    def table_(self) -> tuple[npt.NDArray[np.float64], npt.NDArray[np.float64]]: ...

class HermiteAnamorphosis:
    def __init__(self, degree: int = 30) -> None: ...
    def fit(self, values: ArrayLike, weights: ArrayLike | None = None) -> HermiteAnamorphosis: ...
    def transform(self, values: ArrayLike) -> npt.NDArray[np.float64]: ...
    def inverse_transform(self, scores: ArrayLike) -> npt.NDArray[np.float64]: ...
    @property
    def coefficients_(self) -> npt.NDArray[np.float64]: ...
    @property
    def mean_(self) -> float: ...
    @property
    def variance_(self) -> float: ...
    def block(self, r: float) -> HermiteAnamorphosis: ...
    def grade_tonnage(self, cutoffs: ArrayLike) -> dict[str, npt.NDArray[np.float64]]: ...

class BoxCox:
    def __init__(self, lambda_: float | None = None) -> None: ...
    def fit(self, values: ArrayLike) -> BoxCox: ...
    @property
    def lambda_(self) -> float: ...
    def transform(self, values: ArrayLike) -> npt.NDArray[np.float64]: ...
    def inverse_transform(self, values: ArrayLike) -> npt.NDArray[np.float64]: ...

class PPMT:
    def __init__(
        self, iterations: int = 30, candidates: int = 60, seed: int = 1, marginal: bool = True
    ) -> None: ...
    def fit(self, data: ArrayLike, weights: ArrayLike | None = None) -> PPMT: ...
    def transform(self, data: ArrayLike) -> npt.NDArray[np.float64]: ...
    def inverse_transform(self, data: ArrayLike) -> npt.NDArray[np.float64]: ...

class PCA:
    def __init__(self, standardize: bool = False) -> None: ...
    def fit(self, data: ArrayLike, weights: ArrayLike | None = None) -> PCA: ...
    def transform(self, data: ArrayLike) -> npt.NDArray[np.float64]: ...
    def inverse_transform(self, data: ArrayLike) -> npt.NDArray[np.float64]: ...
    @property
    def components_(self) -> npt.NDArray[np.float64]: ...
    @property
    def explained_variance_(self) -> npt.NDArray[np.float64]: ...
    @property
    def explained_variance_ratio_(self) -> npt.NDArray[np.float64]: ...

class MAF:
    def __init__(self, lag: float, tolerance: float | None = None) -> None: ...
    def fit(self, data: ArrayLike, coords: ArrayLike) -> MAF: ...
    def transform(self, data: ArrayLike) -> npt.NDArray[np.float64]: ...
    def inverse_transform(self, data: ArrayLike) -> npt.NDArray[np.float64]: ...
    @property
    def gammas_(self) -> npt.NDArray[np.float64]: ...

class StepwiseConditional:
    def __init__(self, classes: int = 10) -> None: ...
    def fit(self, data: ArrayLike) -> StepwiseConditional: ...
    def transform(self, data: ArrayLike) -> npt.NDArray[np.float64]: ...
    def inverse_transform(self, data: ArrayLike) -> npt.NDArray[np.float64]: ...

class UniformConditioning:
    def __init__(self, anamorphosis: HermiteAnamorphosis, r_smu: float, r_panel: float) -> None: ...
    def panel_recovery(
        self, panel_grade: float, cutoffs: ArrayLike
    ) -> dict[str, npt.NDArray[np.float64]]: ...
    def localized_grades(self, panel_grade: float, n_smu: int) -> npt.NDArray[np.float64]: ...

class Trend:
    @property
    def degree(self) -> int: ...
    @property
    def coefficients(self) -> npt.NDArray[np.float64]: ...
    def predict(self, coords: ArrayLike) -> npt.NDArray[np.float64]: ...

class Declustering:
    @property
    def mean(self) -> float: ...
    @property
    def cell_size(self) -> float: ...
    @property
    def weights(self) -> npt.NDArray[np.float64]: ...
    @property
    def sizes(self) -> npt.NDArray[np.float64]: ...
    @property
    def means(self) -> npt.NDArray[np.float64]: ...

def detrend(
    coords: ArrayLike, values: ArrayLike, degree: int = 1
) -> tuple[Trend, npt.NDArray[np.float64]]: ...
def cell_declustering(
    coords: ArrayLike,
    values: ArrayLike,
    cell_size: float | None = None,
    sizes: ArrayLike | None = None,
    offsets: int = 25,
    minimize: bool = True,
) -> Declustering: ...
def polygon_declustering(coords: ArrayLike, values: ArrayLike, nodes: int = 10_000) -> Declustering: ...
def affine_correction(
    values: ArrayLike, f: float, weights: ArrayLike | None = None
) -> npt.NDArray[np.float64]: ...
def indirect_lognormal_correction(
    values: ArrayLike, f: float, weights: ArrayLike | None = None
) -> npt.NDArray[np.float64]: ...
def upscale(
    coords: ArrayLike,
    values: ArrayLike,
    block_size: Sequence[float],
    origin: Sequence[float] = (0.0, 0.0, 0.0),
) -> tuple[npt.NDArray[np.float64], npt.NDArray[np.float64], npt.NDArray[np.float64]]: ...
def downscale(
    center: Sequence[float], block_size: Sequence[float], value: float, refine: tuple[int, int, int]
) -> tuple[npt.NDArray[np.float64], npt.NDArray[np.float64]]: ...
def normal_cdf(x: ArrayLike) -> npt.NDArray[np.float64]: ...
def normal_ppf(p: ArrayLike) -> npt.NDArray[np.float64]: ...

class Structure:
    def __init__(
        self, model: str, sill: float, range: float, order: float | None = None, exponent: float | None = None
    ) -> None: ...
    @property
    def model(self) -> str: ...
    @property
    def sill(self) -> float: ...
    @property
    def range(self) -> float: ...

class Variogram:
    def __init__(
        self,
        structures: Sequence[Structure | tuple[str, float, float]],
        nugget: float = 0.0,
        rotation: tuple[float, float, float] = (0.0, 0.0, 0.0),
        ratios: tuple[float, float] = (1.0, 1.0),
    ) -> None: ...
    @staticmethod
    def fit(
        experimental: ExperimentalVariogram, model: str = "spherical", weighting: str = "count"
    ) -> Variogram: ...
    def with_anisotropy(
        self, rotation: tuple[float, float, float], ratios: tuple[float, float]
    ) -> Variogram: ...
    @property
    def nugget(self) -> float: ...
    @property
    def structures(self) -> list[Structure]: ...
    @property
    def rotation(self) -> tuple[float, float, float]: ...
    @property
    def ratios(self) -> tuple[float, float]: ...
    @property
    def sill(self) -> float: ...
    def gamma(self, h: ArrayLike) -> npt.NDArray[np.float64]: ...
    def covariance(self, h: ArrayLike) -> npt.NDArray[np.float64]: ...
    def gamma_between(self, a: ArrayLike, b: ArrayLike) -> npt.NDArray[np.float64]: ...
    def to_json(self) -> str: ...
    @staticmethod
    def from_json(text: str) -> Variogram: ...

class ExperimentalVariogram:
    @property
    def lags(self) -> npt.NDArray[np.float64]: ...
    @property
    def gammas(self) -> npt.NDArray[np.float64]: ...
    @property
    def counts(self) -> npt.NDArray[np.float64]: ...
    def fit(self, model: str = "spherical", weighting: str = "count") -> Variogram: ...

class VariogramMap:
    lags: npt.NDArray[np.float64]
    angles: npt.NDArray[np.float64]
    gammas: npt.NDArray[np.float64]
    counts: npt.NDArray[np.float64]
    ranges: npt.NDArray[np.float64]

class Coregionalization:
    def __init__(
        self,
        nugget: Sequence[Sequence[float]],
        structures: Sequence[tuple[str, float, Sequence[Sequence[float]]]],
        rotation: tuple[float, float, float] = (0.0, 0.0, 0.0),
        ratios: tuple[float, float] = (1.0, 1.0),
    ) -> None: ...
    @property
    def nvar(self) -> int: ...
    def cross_covariance(self, i: int, j: int, a: ArrayLike, b: ArrayLike) -> npt.NDArray[np.float64]: ...

class Transiogram:
    def __init__(self, proportions: Sequence[float], range: float) -> None: ...
    def matrix(self, h: float) -> npt.NDArray[np.float64]: ...

def experimental_variogram(
    coords: ArrayLike,
    values: ArrayLike,
    lag: float,
    max_lag: float,
    azimuth: float | None = None,
    dip: float = 0.0,
    tolerance: float = 22.5,
    bandwidth: float | None = None,
    estimator: str = "matheron",
) -> ExperimentalVariogram: ...
def variogram_map(
    coords: ArrayLike,
    values: ArrayLike,
    lag: float,
    max_lag: float,
    u: Sequence[float] = (1.0, 0.0, 0.0),
    v: Sequence[float] = (0.0, 1.0, 0.0),
    tolerance: float = 22.5,
    steps: int = 36,
    model: str = "spherical",
) -> VariogramMap: ...
def variogram_surface_ranges(
    coords: ArrayLike,
    values: ArrayLike,
    lag: float,
    max_lag: float,
    azimuth_steps: int = 24,
    dip_steps: int = 6,
    tolerance: float = 22.5,
    model: str = "spherical",
) -> tuple[npt.NDArray[np.float64], npt.NDArray[np.float64], npt.NDArray[np.float64]]: ...
def experimental_transiogram(
    coords: ArrayLike, categories: Sequence[int], lag: float, max_lag: float
) -> tuple[npt.NDArray[np.float64], npt.NDArray[np.float64], npt.NDArray[np.float64]]: ...
def change_of_support(
    anamorphosis: HermiteAnamorphosis,
    variogram: Variogram,
    size: Sequence[float],
    discretization: tuple[int, int, int] = (4, 4, 1),
) -> tuple[float, HermiteAnamorphosis]: ...
def block_correlation(
    variogram: Variogram, size: Sequence[float], discretization: tuple[int, int, int] = (4, 4, 1)
) -> float: ...

class Search:
    def __init__(
        self,
        radius: float,
        max_samples: int = 16,
        min_samples: int = 1,
        octant: bool = False,
        max_per_hole: int | None = None,
        rotation: tuple[float, float, float] | None = None,
        ratios: tuple[float, float] | None = None,
    ) -> None: ...
    @property
    def radius(self) -> float: ...
    @property
    def max_samples(self) -> int: ...
    @property
    def min_samples(self) -> int: ...

class _Estimator:
    def __init__(
        self, method: str, search: Search, variogram: Variogram | None = None, **options: Any
    ) -> None: ...
    def fit(self, coords: ArrayLike, values: ArrayLike, holes: Holes | None = None) -> _Estimator: ...
    @property
    def values(self) -> npt.NDArray[np.float64]: ...
    def predict(
        self,
        targets: Any,
        return_variance: bool = False,
        anisotropy: LocalAnisotropy | None = None,
        diagnostics: bool = False,
    ) -> Any: ...
    def cross_validate(self) -> tuple[npt.NDArray[np.float64], npt.NDArray[np.float64]]: ...

class DualKriging:
    def __init__(self, variogram: Variogram, degree: int = 0) -> None: ...
    def fit(self, coords: ArrayLike, values: ArrayLike) -> DualKriging: ...
    def predict(self, targets: Any) -> npt.NDArray[np.float64]: ...

def neighborhood_stats(
    targets: Any,
    coords: ArrayLike,
    values: ArrayLike,
    k: int = 8,
    radius: float = ...,
    variogram: Variogram | None = None,
    holes: Holes | None = None,
) -> dict[str, npt.NDArray[np.float64]]: ...

class SGS:
    def __init__(self, variogram: Variogram, search: Search) -> None: ...
    def fit(
        self,
        coords: ArrayLike,
        values: ArrayLike,
        weights: ArrayLike | None = None,
        holes: Holes | None = None,
    ) -> SGS: ...
    def simulate(
        self,
        targets: Any,
        n: int = 100,
        seed: int = 0,
        cutoffs: Sequence[float] = (),
        quantiles: Sequence[float] = (),
        realizations: bool = False,
        anisotropy: LocalAnisotropy | None = None,
    ) -> SimulationSummary: ...

class TurningBands:
    def __init__(
        self, variogram: Variogram, bands: int = 300, step: float | None = None, search: Search | None = None
    ) -> None: ...
    def fit(
        self,
        coords: ArrayLike,
        values: ArrayLike,
        weights: ArrayLike | None = None,
        holes: Holes | None = None,
    ) -> TurningBands: ...
    def simulate(
        self,
        targets: Any,
        n: int = 100,
        seed: int = 0,
        cutoffs: Sequence[float] = (),
        quantiles: Sequence[float] = (),
        realizations: bool = False,
    ) -> SimulationSummary: ...
    def simulate_to_parquet(
        self,
        path: Path,
        out: Path,
        n: int = 100,
        seed: int = 0,
        cutoffs: Sequence[float] = (),
        quantiles: Sequence[float] = (),
        rows: int = 1_000_000,
    ) -> dict[str, npt.NDArray[np.float64]]: ...

class SIS:
    def __init__(self, variograms: Sequence[Variogram], search: Search) -> None: ...
    def fit(self, coords: ArrayLike, categories: ArrayLike, holes: Holes | None = None) -> SIS: ...
    def simulate(
        self, targets: Any, n: int = 100, seed: int = 0, realizations: bool = False
    ) -> CategoricalSummary: ...

class Plurigaussian:
    def __init__(
        self,
        variogram: Variogram,
        second_variogram: Variogram | None = None,
        proportions: Sequence[float] | None = None,
        regions: Sequence[tuple[float, float, float, float, int]] | None = None,
    ) -> None: ...
    def fit(self, coords: ArrayLike, facies: ArrayLike, holes: Holes | None = None) -> Plurigaussian: ...
    def simulate(
        self, targets: Any, n: int = 100, seed: int = 0, realizations: bool = False
    ) -> CategoricalSummary: ...

class SimulationSummary:
    @property
    def n(self) -> int: ...
    @property
    def mean(self) -> npt.NDArray[np.float64]: ...
    @property
    def variance(self) -> npt.NDArray[np.float64]: ...
    @property
    def std(self) -> npt.NDArray[np.float64]: ...
    @property
    def cutoffs(self) -> list[float]: ...
    @property
    def probability_above(self) -> npt.NDArray[np.float64]: ...
    @property
    def mean_above(self) -> npt.NDArray[np.float64]: ...
    @property
    def quantiles(self) -> list[float]: ...
    @property
    def quantile_values(self) -> npt.NDArray[np.float64]: ...
    @property
    def realization_mean(self) -> npt.NDArray[np.float64]: ...
    @property
    def realization_above(self) -> npt.NDArray[np.float64]: ...
    @property
    def realizations(self) -> npt.NDArray[np.float64] | None: ...

class CategoricalSummary:
    @property
    def n(self) -> int: ...
    @property
    def probabilities(self) -> npt.NDArray[np.float64]: ...
    @property
    def most_likely(self) -> npt.NDArray[np.int64]: ...
    @property
    def entropy(self) -> npt.NDArray[np.float64]: ...
    @property
    def proportions(self) -> npt.NDArray[np.float64]: ...
    @property
    def realizations(self) -> npt.NDArray[np.int64] | None: ...

def gibbs(
    coords: ArrayLike,
    bounds: ArrayLike,
    variogram: Variogram,
    iterations: int = 200,
    burn_in: int = 50,
    seed: int = 1,
) -> npt.NDArray[np.float64]: ...

class Cokriging:
    def __init__(
        self, coregionalization: Coregionalization, search: Search, means: Sequence[float] | None = None
    ) -> None: ...
    def fit(
        self, coords: ArrayLike, values: ArrayLike, variables: Sequence[int], holes: Holes | None = None
    ) -> Cokriging: ...
    def predict(
        self,
        targets: Any,
        variable: int = 0,
        return_variance: bool = False,
        collocated: Mapping[int, ArrayLike] | None = None,
    ) -> Any: ...

class DisjunctiveKriging:
    def __init__(
        self, anamorphosis: HermiteAnamorphosis, variogram: Variogram, search: Search, order: int = 20
    ) -> None: ...
    def fit(self, coords: ArrayLike, values: ArrayLike) -> DisjunctiveKriging: ...
    def predict(self, targets: Any) -> npt.NDArray[np.float64]: ...
    def predict_tonnage(self, targets: Any, cutoff: float) -> npt.NDArray[np.float64]: ...

class Drillholes:
    def __init__(
        self,
        collar: TableLike,
        survey: TableLike,
        intervals: TableLike | None = None,
        hole: str = "HOLEID",
        x: str = "X",
        y: str = "Y",
        z: str = "Z",
        at: str = "DEPTH",
        azimuth: str = "AZIMUTH",
        dip: str | None = "DIP",
        inclination: str | None = None,
        from_: str = "FROM",
        to: str = "TO",
    ) -> None: ...
    @property
    def holes(self) -> list[str]: ...
    def paths(self) -> Table: ...
    def at(self, holes: Sequence[str], depths: ArrayLike) -> npt.NDArray[np.float64]: ...
    def samples(self) -> PointSet: ...
    def composite(self, length: float, grades: Sequence[str], domain: str | None = None) -> PointSet: ...
    def __len__(self) -> int: ...

def closure(parts: ArrayLike, total: float = 1.0) -> npt.NDArray[np.float64]: ...
def clr(parts: ArrayLike) -> npt.NDArray[np.float64]: ...
def clr_inverse(coords: ArrayLike) -> npt.NDArray[np.float64]: ...
def alr(parts: ArrayLike) -> npt.NDArray[np.float64]: ...
def alr_inverse(coords: ArrayLike) -> npt.NDArray[np.float64]: ...
def ilr(parts: ArrayLike) -> npt.NDArray[np.float64]: ...
def ilr_inverse(coords: ArrayLike) -> npt.NDArray[np.float64]: ...
def aitchison_distance(a: ArrayLike, b: ArrayLike) -> npt.NDArray[np.float64]: ...

class Mesh:
    def __init__(self, vertices: ArrayLike, triangles: ArrayLike, crs: str | None = None) -> None: ...
    @property
    def vertices(self) -> npt.NDArray[np.float64]: ...
    @property
    def triangles(self) -> npt.NDArray[np.int64]: ...
    @property
    def bounds(self) -> tuple[list[float], list[float]] | None: ...
    @property
    def crs(self) -> str | None: ...
    @property
    def is_closed(self) -> bool: ...
    @property
    def analysis(self) -> dict[str, int | bool]: ...
    @property
    def area(self) -> float: ...
    @property
    def volume(self) -> float: ...
    @property
    def vertex_attributes(self) -> Table: ...
    @property
    def face_attributes(self) -> Table: ...
    def with_vertex_column(self, name: str, values: ArrayLike | Sequence[str]) -> Mesh: ...
    def with_face_column(self, name: str, values: ArrayLike | Sequence[str]) -> Mesh: ...
    def contains(self, points: ArrayLike) -> npt.NDArray[np.bool_]: ...
    def winding_number(self, points: ArrayLike) -> npt.NDArray[np.float64]: ...
    def distance(self, points: ArrayLike, signed: bool = False) -> npt.NDArray[np.float64]: ...
    def proportion(
        self, blocks: Any, size: Sequence[float] | None = None, discretization: int = 4
    ) -> npt.NDArray[np.float64]: ...

class PolygonSelector:
    def __init__(
        self,
        rings: Sequence[ArrayLike],
        closed: bool = False,
        z_min: float | None = None,
        z_max: float | None = None,
    ) -> None: ...
    def contains(self, points: ArrayLike) -> npt.NDArray[np.bool_]: ...

def point_in_polygon(points: ArrayLike, polygon: ArrayLike) -> npt.NDArray[np.bool_]: ...
def polygon_distance(
    points: ArrayLike, polygon: ArrayLike, signed: bool = False
) -> npt.NDArray[np.float64]: ...
def assign_domain(
    targets: Any,
    coords: ArrayLike | None = None,
    domains: Sequence[str] | None = None,
    method: str = "nearest",
    mesh: Mesh | None = None,
) -> tuple[list[str], npt.NDArray[np.float64]]: ...
def block_shell(model: BlockModel, column: str | None = None) -> Mesh: ...
def merge_intervals(
    left: TableLike, right: TableLike, hole: str = "HOLEID", from_: str = "FROM", to: str = "TO"
) -> Table: ...

class LocalAnisotropy:
    def __init__(self, coords: ArrayLike, angles: ArrayLike, ratios: ArrayLike) -> None: ...
    @staticmethod
    def from_grid(
        model: BlockModel, column: str, window: int = 2, ratios: tuple[float, float] | None = None
    ) -> LocalAnisotropy: ...
    @staticmethod
    def from_points(
        coords: ArrayLike, k: int = 20, ratios: tuple[float, float] | None = None
    ) -> LocalAnisotropy: ...
    @staticmethod
    def from_mesh(
        mesh: Mesh, targets: Any, major: str = "dip", ratios: tuple[float, float] = (1.0, 0.2)
    ) -> LocalAnisotropy: ...
    def smooth(self, radius: float) -> LocalAnisotropy: ...
    def at(self, targets: Any) -> LocalAnisotropy: ...
    @property
    def coords(self) -> npt.NDArray[np.float64]: ...
    @property
    def angles(self) -> npt.NDArray[np.float64]: ...
    @property
    def ratios(self) -> npt.NDArray[np.float64]: ...
    def __len__(self) -> int: ...

class ImplicitModel:
    def __init__(
        self,
        engine: str = "rbf",
        kernel: str = "biharmonic",
        variogram: Variogram | None = None,
        drift_degree: int = 1,
        smoothing: float = 0.0,
        rotation: tuple[float, float, float] | None = None,
        ratios: tuple[float, float] | None = None,
    ) -> None: ...
    def fit(
        self,
        coords: ArrayLike | None = None,
        values: ArrayLike | None = None,
        cutoff: float | None = None,
        boundaries: ArrayLike | None = None,
        planes: ArrayLike | None = None,
        lineations: ArrayLike | None = None,
    ) -> ImplicitModel: ...
    def evaluate(self, targets: Any, gradient: bool = False, variance: bool = False) -> Any: ...
    def isosurface(self, block_model: BlockModel, isovalue: float = 0.0, closed: bool = False) -> Mesh: ...
    @property
    def report(self) -> dict[str, Any] | None: ...

def write_parquet(path: Path, data: PointSet | BlockModel | TableLike) -> None: ...
def read_parquet(path: Path) -> PointSet | BlockModel | Table: ...

class BlockModelFile:
    def __init__(self, path: Path) -> None: ...
    @property
    def origin(self) -> list[float]: ...
    @property
    def size(self) -> list[float]: ...
    @property
    def count(self) -> list[int]: ...
    @property
    def rotation(self) -> list[float]: ...
    @property
    def crs(self) -> str | None: ...
    @property
    def column_names(self) -> list[str]: ...
    def chunks(self, rows: int = 1_000_000, columns: Sequence[str] | None = None) -> Iterator[BlockModel]: ...
    def __len__(self) -> int: ...

def map_blocks(
    path: Path,
    out: Path,
    func: Callable[[BlockModel], Mapping[str, ArrayLike]],
    rows: int = 1_000_000,
    keep: bool = True,
) -> None: ...
def read_mesh(path: Path) -> Mesh: ...
def write_mesh(path: Path, mesh: Mesh, ascii: bool = False) -> None: ...
def describe(
    values: ArrayLike,
    weights: ArrayLike | None = None,
    quantiles: Sequence[float] = (0.1, 0.25, 0.5, 0.75, 0.9),
) -> dict[str, Any]: ...
def swath(
    coords: ArrayLike,
    values: ArrayLike,
    width: float,
    azimuth: float | None = None,
    axis: str | None = None,
    weights: ArrayLike | None = None,
) -> dict[str, npt.NDArray[np.float64] | list[int]]: ...
def contact(
    coords: ArrayLike,
    values: ArrayLike,
    domains: Holes,
    holes: Holes,
    inside: int | str,
    outside: int | str,
    max_distance: float,
    bin: float,
) -> dict[str, npt.NDArray[np.float64] | list[int]]: ...
def capping(
    values: ArrayLike, weights: ArrayLike | None = None, caps: ArrayLike | None = None
) -> dict[str, npt.NDArray[np.float64]]: ...
def h_scatter(
    coords: ArrayLike,
    values: ArrayLike,
    lag: float,
    tolerance: float,
    azimuth: float | None = None,
    dip: float = 0.0,
    angle_tolerance: float = 22.5,
    other: ArrayLike | None = None,
) -> tuple[npt.NDArray[np.float64], npt.NDArray[np.float64], float]: ...
def correlation(
    data: ArrayLike, weights: ArrayLike | None = None, method: str = "pearson"
) -> npt.NDArray[np.float64]: ...
def smooth_classes(
    model: BlockModel, classes: ArrayLike, window: tuple[int, int, int] = (3, 3, 1), iterations: int = 1
) -> npt.NDArray[Any]: ...
