from collections.abc import Mapping, Sequence
from os import PathLike
from typing import Any, TypeAlias

import numpy as np
import numpy.typing as npt

__version__: str

ArrayLike = npt.ArrayLike
TableLike: TypeAlias = (
    Any  # Arrow PyCapsule object (pyarrow, polars, Table, PointSet) or Mapping[str, ArrayLike]
)
Path: TypeAlias = str | PathLike[str]

class Table:
    def __init__(self, data: TableLike | Mapping[str, ArrayLike]) -> None: ...
    @property
    def num_rows(self) -> int: ...
    @property
    def column_names(self) -> list[str]: ...
    def column(self, name: str) -> npt.NDArray[np.float64] | list[str | None]: ...
    def __getitem__(self, name: str) -> npt.NDArray[np.float64] | list[str | None]: ...
    def __len__(self) -> int: ...
    def to_polars(self) -> Any: ...
    def to_pyarrow(self) -> Any: ...
    def to_pandas(self) -> Any: ...
    def __arrow_c_schema__(self) -> object: ...
    def __arrow_c_array__(self, requested_schema: object | None = None) -> tuple[object, object]: ...
    def __arrow_c_stream__(self, requested_schema: object | None = None) -> object: ...

class PointSet:
    def __init__(
        self,
        coords: ArrayLike,
        attributes: TableLike | Mapping[str, ArrayLike] | None = None,
        crs: str | None = None,
    ) -> None: ...
    @staticmethod
    def from_table(
        table: TableLike, x: str = "X", y: str = "Y", z: str | None = None, crs: str | None = None
    ) -> PointSet: ...
    @property
    def coords(self) -> npt.NDArray[np.float64]: ...
    @property
    def attributes(self) -> Table: ...
    @property
    def crs(self) -> str | None: ...
    def to_table(self) -> Table: ...
    def __getitem__(self, name: str) -> npt.NDArray[np.float64] | list[str | None]: ...
    def __len__(self) -> int: ...
    def __arrow_c_stream__(self, requested_schema: object | None = None) -> object: ...

class BlockModel:
    def __init__(
        self,
        origin: Sequence[float],
        size: Sequence[float],
        count: Sequence[int],
        rotation: tuple[float, float, float] = (0.0, 0.0, 0.0),
        attributes: TableLike | Mapping[str, ArrayLike] | None = None,
        index: npt.NDArray[np.uint64] | None = None,
        crs: str | None = None,
    ) -> None: ...
    @property
    def origin(self) -> list[float]: ...
    @property
    def size(self) -> list[float]: ...
    @property
    def count(self) -> list[int]: ...
    @property
    def rotation(self) -> list[float]: ...
    @property
    def crs(self) -> str | None: ...
    @property
    def index(self) -> npt.NDArray[np.uint64] | None: ...
    @property
    def centroids(self) -> npt.NDArray[np.float64]: ...
    @property
    def attributes(self) -> Table: ...
    def mask(self, keep: npt.NDArray[np.bool_]) -> BlockModel: ...
    def to_regular(self) -> BlockModel: ...
    def to_table(self) -> Table: ...
    def __getitem__(self, name: str) -> npt.NDArray[np.float64] | list[str | None]: ...
    def __len__(self) -> int: ...
    def __arrow_c_stream__(self, requested_schema: object | None = None) -> object: ...

def read_csv(path: Path, nodata: Sequence[str] | None = None, delimiter: str = ",") -> Table: ...
def write_csv(path: Path, table: TableLike) -> None: ...
def read_gslib(path: Path, nodata: Sequence[str] | None = None) -> Table: ...
def write_gslib(path: Path, table: TableLike, missing: float = -999.0) -> None: ...
