from collections.abc import Mapping, Sequence
from os import PathLike
from typing import Any, TypeAlias

import numpy as np
import numpy.typing as npt

__version__: str

ArrayLike = npt.ArrayLike
TableLike: TypeAlias = (
    Any  # Arrow PyCapsule object (pyarrow, polars, Table, PointSet) or Mapping[str, ArrayLike]
)
Path: TypeAlias = str | PathLike[str]

class Table:
    def __init__(self, data: TableLike | Mapping[str, ArrayLike]) -> None: ...
    @property
    def num_rows(self) -> int: ...
    @property
    def column_names(self) -> list[str]: ...
    def column(self, name: str) -> npt.NDArray[np.float64] | list[str | None]: ...
    def __getitem__(self, name: str) -> npt.NDArray[np.float64] | list[str | None]: ...
    def __len__(self) -> int: ...
    def to_polars(self) -> Any: ...
    def to_pyarrow(self) -> Any: ...
    def to_pandas(self) -> Any: ...
    def __arrow_c_schema__(self) -> object: ...
    def __arrow_c_array__(self, requested_schema: object | None = None) -> tuple[object, object]: ...
    def __arrow_c_stream__(self, requested_schema: object | None = None) -> object: ...

class PointSet:
    def __init__(
        self,
        coords: ArrayLike,
        attributes: TableLike | Mapping[str, ArrayLike] | None = None,
        crs: str | None = None,
    ) -> None: ...
    @staticmethod
    def from_table(
        table: TableLike, x: str = "X", y: str = "Y", z: str | None = None, crs: str | None = None
    ) -> PointSet: ...
    @property
    def coords(self) -> npt.NDArray[np.float64]: ...
    @property
    def attributes(self) -> Table: ...
    @property
    def crs(self) -> str | None: ...
    def to_table(self) -> Table: ...
    def __getitem__(self, name: str) -> npt.NDArray[np.float64] | list[str | None]: ...
    def __len__(self) -> int: ...
    def __arrow_c_stream__(self, requested_schema: object | None = None) -> object: ...

class BlockModel:
    def __init__(
        self,
        origin: Sequence[float],
        size: Sequence[float],
        count: Sequence[int],
        rotation: tuple[float, float, float] = (0.0, 0.0, 0.0),
        attributes: TableLike | Mapping[str, ArrayLike] | None = None,
        index: npt.NDArray[np.uint64] | None = None,
        crs: str | None = None,
    ) -> None: ...
    @property
    def origin(self) -> list[float]: ...
    @property
    def size(self) -> list[float]: ...
    @property
    def count(self) -> list[int]: ...
    @property
    def rotation(self) -> list[float]: ...
    @property
    def crs(self) -> str | None: ...
    @property
    def index(self) -> npt.NDArray[np.uint64] | None: ...
    @property
    def centroids(self) -> npt.NDArray[np.float64]: ...
    @property
    def attributes(self) -> Table: ...
    def mask(self, keep: npt.NDArray[np.bool_]) -> BlockModel: ...
    def to_regular(self) -> BlockModel: ...
    def to_table(self) -> Table: ...
    def __getitem__(self, name: str) -> npt.NDArray[np.float64] | list[str | None]: ...
    def __len__(self) -> int: ...
    def __arrow_c_stream__(self, requested_schema: object | None = None) -> object: ...

def read_csv(path: Path, nodata: Sequence[str] | None = None, delimiter: str = ",") -> Table: ...
def write_csv(path: Path, table: TableLike) -> None: ...
def read_gslib(path: Path, nodata: Sequence[str] | None = None) -> Table: ...
def write_gslib(path: Path, table: TableLike, missing: float = -999.0) -> None: ...

class NormalScore:
    def __init__(self) -> None: ...
    def fit(self, values: ArrayLike, weights: ArrayLike | None = None) -> NormalScore: ...
    def fit_transform(
        self, values: ArrayLike, weights: ArrayLike | None = None
    ) -> npt.NDArray[np.float64]: ...
    def transform(self, values: ArrayLike) -> npt.NDArray[np.float64]: ...
    def inverse_transform(self, scores: ArrayLike) -> npt.NDArray[np.float64]: ...
    @property
    def table_(self) -> tuple[npt.NDArray[np.float64], npt.NDArray[np.float64]]: ...

class HermiteAnamorphosis:
    def __init__(self, degree: int = 30) -> None: ...
    def fit(self, values: ArrayLike, weights: ArrayLike | None = None) -> HermiteAnamorphosis: ...
    def transform(self, values: ArrayLike) -> npt.NDArray[np.float64]: ...
    def inverse_transform(self, scores: ArrayLike) -> npt.NDArray[np.float64]: ...
    @property
    def coefficients_(self) -> npt.NDArray[np.float64]: ...
    @property
    def mean_(self) -> float: ...
    @property
    def variance_(self) -> float: ...
    def block(self, r: float) -> HermiteAnamorphosis: ...
    def grade_tonnage(self, cutoffs: ArrayLike) -> dict[str, npt.NDArray[np.float64]]: ...

class BoxCox:
    def __init__(self, lambda_: float | None = None) -> None: ...
    def fit(self, values: ArrayLike) -> BoxCox: ...
    @property
    def lambda_(self) -> float: ...
    def transform(self, values: ArrayLike) -> npt.NDArray[np.float64]: ...
    def inverse_transform(self, values: ArrayLike) -> npt.NDArray[np.float64]: ...

class PPMT:
    def __init__(self, iterations: int = 30, candidates: int = 60, seed: int = 1) -> None: ...
    def fit(self, data: ArrayLike) -> PPMT: ...
    def transform(self, data: ArrayLike) -> npt.NDArray[np.float64]: ...
    def inverse_transform(self, data: ArrayLike) -> npt.NDArray[np.float64]: ...

class UniformConditioning:
    def __init__(self, anamorphosis: HermiteAnamorphosis, r_smu: float, r_panel: float) -> None: ...
    def panel_recovery(
        self, panel_grade: float, cutoffs: ArrayLike
    ) -> dict[str, npt.NDArray[np.float64]]: ...
    def localized_grades(self, panel_grade: float, n_smu: int) -> npt.NDArray[np.float64]: ...

class Trend:
    @property
    def degree(self) -> int: ...
    @property
    def coefficients(self) -> npt.NDArray[np.float64]: ...
    def predict(self, coords: ArrayLike) -> npt.NDArray[np.float64]: ...

class Declustering:
    @property
    def mean(self) -> float: ...
    @property
    def cell_size(self) -> float: ...
    @property
    def weights(self) -> npt.NDArray[np.float64]: ...
    @property
    def sizes(self) -> npt.NDArray[np.float64]: ...
    @property
    def means(self) -> npt.NDArray[np.float64]: ...

def detrend(
    coords: ArrayLike, values: ArrayLike, degree: int = 1
) -> tuple[Trend, npt.NDArray[np.float64]]: ...
def cell_declustering(
    coords: ArrayLike,
    values: ArrayLike,
    cell_size: float | None = None,
    sizes: ArrayLike | None = None,
    offsets: int = 25,
    minimize: bool = True,
) -> Declustering: ...
def polygon_declustering(coords: ArrayLike, values: ArrayLike, nodes: int = 10_000) -> Declustering: ...
def affine_correction(
    values: ArrayLike, f: float, weights: ArrayLike | None = None
) -> npt.NDArray[np.float64]: ...
def indirect_lognormal_correction(
    values: ArrayLike, f: float, weights: ArrayLike | None = None
) -> npt.NDArray[np.float64]: ...
def upscale(
    coords: ArrayLike,
    values: ArrayLike,
    block_size: Sequence[float],
    origin: Sequence[float] = (0.0, 0.0, 0.0),
) -> tuple[npt.NDArray[np.float64], npt.NDArray[np.float64], npt.NDArray[np.float64]]: ...
def downscale(
    center: Sequence[float], block_size: Sequence[float], value: float, refine: tuple[int, int, int]
) -> tuple[npt.NDArray[np.float64], npt.NDArray[np.float64]]: ...
def normal_cdf(x: ArrayLike) -> npt.NDArray[np.float64]: ...
def normal_ppf(p: ArrayLike) -> npt.NDArray[np.float64]: ...
