[package]
name = "boitata-io"
description = "Table and mesh readers and writers"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
arrow-array.workspace = true
arrow-cast.workspace = true
arrow-csv.workspace = true
arrow-schema.workspace = true
arrow-select.workspace = true
boitata-core.workspace = true
dxf.workspace = true
parquet.workspace = true
rayon.workspace = true
regex.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tiff.workspace = true

[dev-dependencies]
criterion.workspace = true

[[bench]]
name = "parquet"
harness = false

[lints]
workspace = true
